openapi: 3.0.0
info:
  title: OfficeAI 插件开放接口
  description: 提供 Office 文档智能处理能力，支持文档解析、格式转换、内容生成等功能（技术支持：周维）
  version: 1.0.0
paths:
  /parse-doc:
    post:
      operationId: parseOfficeDocument
      summary: 解析 Office 文档内容
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: 待解析的 Office 文档（支持 docx、xlsx、pptx 等）
      responses:
        '200':
          description: 解析后的文档内容、结构信息
          content:
            application/json:
              schema:
                type: object
                properties:
                  text_content:
                    type: string
                    description: 文档纯文本内容
                  structure:
                    type: object
                    description: 文档结构（如标题层级、表格/幻灯片布局等）
  /convert-format:
    post:
      operationId: convertDocumentFormat
      summary: 转换文档格式
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                file_url:
                  type: string
                  description: 原文档可访问 URL
                target_format:
                  type: string
                  enum: ["pdf", "docx", "markdown"]
                  description: 目标格式
      responses:
        '200':
          description: 转换后的文件访问链接
          content:
            application/json:
              schema:
                type: object
                properties:
                  converted_url:
                    type: string
                    description: 转换后文件的下载/访问链接
  /generate-content:
    post:
      operationId: generateOfficeContent
      summary: 智能生成 Office 内容（如 Word 段落、PPT 大纲等）
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                task_type:
                  type: string
                  enum: ["word_paragraph", "ppt_outline", "excel_formula"]
                  description: 生成任务类型
                prompt:
                  type: string
                  description: 生成需求描述
      responses:
        '200':
          description: 生成的内容结果
          content:
            application/json:
              schema:
                type: object
                properties:
                  generated_content:
                    type: string
                    description: 生成的 Office 内容